// Generated by CoffeeScript 1.7.0
(function() {
  var EventEmitter, Use,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require('events')).EventEmitter;

  module.exports = function(game, opts) {
    return new Use(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['voxel-reach', 'voxel-registry', 'voxel-inventory-hotbar']
  };

  Use = (function(_super) {
    __extends(Use, _super);

    function Use(game, opts) {
      var _ref, _ref1, _ref2;
      this.game = game;
      this.reach = (function() {
        var _ref1;
        if ((_ref = (_ref1 = game.plugins) != null ? _ref1.get('voxel-reach') : void 0) != null) {
          return _ref;
        } else {
          throw new Error('voxel-use requires "voxel-reach" plugin');
        }
      })();
      this.registry = (function() {
        var _ref2;
        if ((_ref1 = (_ref2 = game.plugins) != null ? _ref2.get('voxel-registry') : void 0) != null) {
          return _ref1;
        } else {
          throw new Error('voxel-use requires "voxel-registry" plugin');
        }
      })();
      this.inventoryHotbar = (function() {
        var _ref3;
        if ((_ref2 = (_ref3 = game.plugins) != null ? _ref3.get('voxel-inventory-hotbar') : void 0) != null) {
          return _ref2;
        } else {
          throw new Error('voxel-use requires "voxel-inventory-hotbar" plugin');
        }
      })();
      this.enable();
    }

    Use.prototype.enable = function() {
      return this.reach.on('use', this.onInteract = (function(_this) {
        return function(target) {
          var clickedBlock, clickedBlockID, consumeCount, held, preventDefault, props, ret, _ref;
          if (((target != null ? target.voxel : void 0) != null) && !_this.game.buttons.crouch) {
            clickedBlockID = _this.game.getBlock(target.voxel);
            clickedBlock = _this.registry.getBlockName(clickedBlockID);
            props = _this.registry.getBlockProps(clickedBlock);
            if (props.onInteract != null) {
              preventDefault = props.onInteract(target);
              if (preventDefault) {
                return;
              }
            }
          }
          held = (_ref = _this.inventoryHotbar) != null ? _ref.held() : void 0;
          if (held != null ? held.item : void 0) {
            props = _this.registry.getItemProps(held.item);
            if (props != null ? props.onUse : void 0) {
              ret = props.onUse(held, target);
              if (typeof ret === 'undefined') {

              } else if (typeof ret === 'number' || typeof ret === 'boolean') {
                consumeCount = ret | 0;
                return _this.inventoryHotbar.takeHeld(consumeCount);
              } else if (typeof ret === 'object') {
                return _this.inventoryHotbar.replaceHeld(ret);
              }
            } else if (_this.registry.isBlock(held.item)) {
              return _this.inventoryHotbar.replaceHeld(_this.useBlock(target, held));
            }
          } else {
            return console.log('waving');
          }
        };
      })(this));
    };

    Use.prototype.useBlock = function(target, held) {
      var currentBlockID, taken;
      if (!this.game.canCreateBlock(target != null ? target.adjacent : void 0)) {
        console.log('blocked');
        return held;
      }
      taken = held.splitPile(1);
      if (held.count === 0) {
        held = void 0;
      }
      if (taken == null) {
        console.log('nothing in this inventory slot to use');
        return held;
      }
      currentBlockID = this.registry.getBlockID(taken.item);
      this.game.setBlock(target.adjacent, currentBlockID);
      return held;
    };

    Use.prototype.disable = function() {
      return this.reach.removeListener('use', this.onInteract);
    };

    return Use;

  })(EventEmitter);

}).call(this);
